main: sdfeconomy.SDFEconomy
name: ${project.name}
version: ${project.version}
description: ${project.description}
authors: [Omwah, thesbros]
softdepend: [Vault, Multiverse-Inventories]

commands:
    sdfeconomy:
        description: Manipulate and query player balances and banks
        aliases: [economy, econ, ec]
        usage: /sdfeconomy help - For more information
    balance:
        description: "Retrieve a player's account balance"
        aliases: [bal]
        usage: /balance ? - For more information
    pay:
        description: "Pay another player"
        usage: /pay ? - For more information

permissions:
    sdfeconomy.*:
        description: Give access to all SDFEconomy commands
        children:
          sdfeconomy.use_account: true
          sdfeconomy.use_bank: true
          sdfeconomy.pay_players: true
          sdfeconomy.see_top_balances: true
          sdfeconomy.admin: true 
    sdfeconomy.use_account:
        description: Allow usage of a player account
        default: true
    sdfeconomy.use_bank:
        description: Allow usage of bank accounts
        default: true
    sdfeconomy.pay_players:
        description: Allow paying other players
        default: true
    sdfeconomy.see_top_balances:
        description: See other player's balances in the top display
        default: false
    sdfeconomy.admin:
        description: Allow access to administration commands
        default: op
